---
root: true
env:
  browser: true
  node: true
  es6: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
plugins:
  - '@typescript-eslint'
  - react
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
rules:
  'prettier/prettier': 'error'
  '@typescript-eslint/explicit-function-return-type': 0
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  'react/react-in-jsx-scope': 0
  'react/prop-types': 0
  'react/jsx-uses-react': error
  'react/jsx-uses-vars': error
settings:
  react:
    version: detect
